Api features
m15e/weather-app-js pull request #1
Opened 2020-11-30 15:29 UTC by m15e

- [ ] app fetches weather data from api upon user inputing location

- [ ] app has switch to toggle between F/C temperature units

- [ ] uses webpack

- [ ] app meets ODIN project requirements

2020-11-30 15:43 UTC, m15e commented
NOTE TO TSE: remote linter jobs not working for some reason, locally all tests are passing, any advice on how to fix this would be appreciated

2020-11-30 20:23 UTC, mikenath223 requested changes
### Hello @m15e  👋

**Good work here. 👌**

- [ ] Kindly check the comments on your code for changes.

- [ ] OPTIONAL - Consider adding a loading icon to display while retrieving info.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-11-30 20:24 UTC, mikenath223 commented on package.json
> +  },
- [ ] Kindly include the necessary scripts for webpack.
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

```

2020-12-01 07:49 UTC, bellom approved these changes
## Hi @m15e  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_*

2020-12-02 15:54 UTC, merged